name: Publish Documentation

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.COMMAND_STRING }}
          env:
            API_KEY: ${{ secrets.COMMAND_STRING }}
